### ISSUE TITLE
Update to Shopware 6.6

### ISSUE THREAD

**Issue by azngeek** [klaviyo/shopware-klaviyo#1]
What is the state of the Shopware 6.6 update? Are there any plans?

**Comment by azngeek** [comment]
Are there any news on the current state of the update? :)

**Comment by wannevancamp** [comment]
@Vildulv, thanks for the compatibility of Shopware 6.6. Unfortunately, version 3.0.0 is not yet available on Packagist, therefor we can't install the extension through Composer. 
https://packagist.org/packages/klaviyo/shopware-klaviyo

**Comment by Vildulv** [comment]
> @Vildulv, thanks for the compatibility of Shopware 6.6. Unfortunately, version 3.0.0 is not yet available on Packagist, therefor we can't install the extension through Composer. https://packagist.org/packages/klaviyo/shopware-klaviyo

@wannevancamp  Thank you for your response, we will solve this problem soon

**Comment by azngeek** [comment]
Perfect. We are also waiting for this.

**Comment by Vildulv** [comment]
> Perfect. We are also waiting for this.

Already done.
