### ISSUE TITLE
[3.0.0] - Plugin breaks Promotions Panel in Shopware Administration

### ISSUE THREAD

**Issue by StepByWeb** [klaviyo/shopware-klaviyo#2]
### Expected Behavior

When navigating to the Promotions panel, it should show.

### Current Behavior

When navigating to the Promotions panel, it doesn't show.

### Steps to Reproduce

1. Install Klaviyo plugin (v 3.0.0)
2. Navigate to Promotions Panel

### Detailed description

When navigating to the Promotions panel, only a white screen is presented to the Admim user (see screenshot). The dev tools show an syntax error in the compiled JavaScript assets preventing the panel from rendering.

The error doesn't occure when deactivating the plugin.

#### System: 
Shopware 6.6.4.1

#### Browser:
Tested on Chrome 127 and Firefox 128

#### Additional details

Screenshot with error message

![image](https://github.com/user-attachments/assets/4335ca01-68c1-4bf9-8910-1dc907d0a739)

**Comment by coreybalint-klaviyo** [comment]
Hello! The team was able to look into this issue and it should be resolved at this time. If you are still experiencing any concerns on it - please let me know and we can take a further look.

**Comment by NghiaDTr** [comment]
Hi guys, do we have any updates about this?

**Comment by coreybalint-klaviyo** [comment]
Hi @NghiaDTr - are you experiencing issues on this? If so - I'll flag it to the team to review, as after the previous update it seemed to have been resolved.

**Comment by NghiaDTr** [comment]
Hi @coreybalint-klaviyo, yes I am still suffering the same problem with same errors with @StepByWeb. I am on Shopware v6.6.5.1 and with Klaviyo v3.0.0

**Comment by coreybalint-klaviyo** [comment]
Thanks for letting me know. We'll look into this.

**Comment by Vhulcan** [comment]
Having the same issue. Someone already made fix for it: https://github.com/klaviyo/shopware-klaviyo/pull/7

**Comment by coreybalint-klaviyo** [comment]
Thanks for pointing out. We're on it!

**Comment by CBrach** [comment]
Quick heads up, we're still experiencing the same issue.

Shopware 6.6.5.1 with plugin version 3.1.0

**Comment by CBrach** [comment]
@coreybalint-klaviyo Any news on this?

**Comment by coreybalint-klaviyo** [comment]
@CBrach - the team is working on an update. An initial fix didn't fully clear the issue, so we're working on an additional update here.

**Comment by coreybalint-klaviyo** [comment]
We’re pleased to inform you that we have addressed the issue affecting the Promotions page in the Klaviyo - Shopware integration (v6.6).

What You Need to Do: Please update your software to the latest version of the Klaviyo extension (3.1.1). Once updated, you should find that the Promotions page functions as expected.

If you have any questions or need further assistance, feel free to reach out to us.

Thank you for your patience!
