### ISSUE TITLE
Error when activating master 3.x.x

### ISSUE THREAD

**Issue by Valito-sw** [klaviyo/shopware-klaviyo#3]
Hey there,

i get this following error when i'm trying to activate the new Version of this plugin for SW6.6:

  [ErrorException]                                                                                                                                                                                    
  Warning: require(/xxx/xxx/xxx/xxx/xxx/custom/plugins/shopware-klaviyo-master-3.x.x/vendor/composer/../twig/twig/src/Resources/core.php): Failed to open stream: No such file   
   or directory

Do you have an idea why this error occurs?
Thank you very much :)

**Comment by coreybalint-klaviyo** [comment]
Hello - can you please confirm which version of shopware you're using today?

**Comment by Valito-sw** [comment]
Hey, i am using SW 6.6.1.2

**Comment by coreybalint-klaviyo** [comment]
We suggest upgrading to the most recent version available (6.6.4.1). We suspect there is a shopware bug with the earlier version, and this will allow you to update properly.

**Comment by Valito-sw** [comment]
For us that is not a very suitable solution because other plugins are not ready for the most recent version. If we update now we create more painpoints for ourselfes. Is there any chance for you to look into that problem a little bit deeper and give us a hint? We want to go live soonish with our new shop and integrate klaviyo is a main criteria in our project.

**Comment by coreybalint-klaviyo** [comment]
We'll have the team look into some alternatives and get back to you soon. Appreciate the patience!

**Comment by Vhulcan** [comment]
Having the same issue. Someone already made fix for it: #7

**Comment by coreybalint-klaviyo** [comment]
Hi all - we have completed an update here that should now resolve this issue. The update has been pushed out, and you can find the installation information here: https://help.klaviyo.com/hc/en-us/articles/13001662470939.  If you have any additional questions, please let us know.
